# Needed to checkout SVN Code Only
resource_types:
#- name: pull-request
#  type: docker-image
#  source:
#    repository: robophred/concourse-svn-resource
#    tag: alpha

- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

resources:
- name: resource-main-code
  type: git
  source:
    ignore_paths: version
    uri: https://github.com/dunc101/policynoteboot.git

- name: resource-dev-integration-code
  type: git
  source:
    uri: https://github.com/dunc101/policynoteboot.git
    
- name: resource-test-integration-code
  type: git
  source:
    uri: https://github.com/dunc101/policynoteboot.git
    
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/dunc101/policynoteboot.git
    branch: master
    file: version
    username: ((github-username))
    password: ((github-password))
    
# nexus repo
- name: artifact
  type: maven-resource
  source:
    url: http://maven01.ipacc.com:8081/nexus/content/repositories/infinity-releases
    snapshot_url: http://maven01.ipacc.com:8081/nexus/content/repositories/infinity-snapshots
    artifact: com.ipacc.services:policynoteboot:jar
    username: ((nexus-username))
    password: ((nexus-password))
# SVN Resource of my main project that I want to deploy
#- name: resource-main-code
#  type: pull-request
#  source:
#    repository: svn://cvs01.ipacc.com/SOARepository/SOAPolicy/PolicyNoteService/trunk-jboss
#    username: ((svn-username))
#    password: ((svn-password))
# SVN Location of my integration tests for dev
#- name: resource-dev-integration-code
#  type: pull-request
#  source:
#    repository: svn://cvs01.ipacc.com/SOARepository/SOAPolicy/PolicyNoteService/trunk-jboss
#    username: ((svn-username))
#    password: ((svn-password))
# SVN Location of my integration tests for test
#- name: resource-test-integration-code
#  type: pull-request
#  source:
#    repository: svn://cvs01.ipacc.com/SOARepository/SOAPolicy/PolicyNoteService/trunk-jboss
#    username: ((svn-username))
#    password: ((svn-password))
# Resource to automatically update our version
#- name: version
#  type: semver
#  source:
#    driver: git
#    uri: git@github.com:concourse/concourse.git
#    branch: version
#    file: version
    
# PCF Deployment to Dev Space Resource
- name: resource-deploy-dev
  type: cf
  source:
    api: https://api.system.cf.ipacc.com
    username: ((cf-username-dev))
    password: ((cf-password-dev))
    organization: ProdAndPricing
    space: Dev

# PCF Deployment to Test Space Resource
- name: resource-deploy-test
  type: cf
  source:
    api: https://api.system.cf.ipacc.com
    username: ((cf-username-test))
    password: ((cf-password-test))
    organization: ProdAndPricing
    space: Test
          
jobs:
- name: build-and-unit-test
  serial: true
  plan: 
  - get: resource-main-code
    trigger: true
  - task: build
    # produces a folder named /out with the manifest.yml and app.jar in it that was built
    file: resource-main-code/scripts/ci/build-and-unit-test.yml
  # Upload the produced to Nexus.
  - put: artifact
    params:
      file: out/app.jar
      pom_file: resource-main-code/policynoteboot/pom.xml

# Deploy to PCF Dev space
- name: deploy-dev-space
  plan:
  - get: resource-main-code
  - get: artifact
    trigger: true
    passed: [build-and-unit-test]
  - put: resource-deploy-dev
    params:
      manifest: resource-main-code/manifest-dev.yml
      path: artifact/*.jar

# Checkout and run dev suite integration tests    
- name: dev-integration-tests
  serial: true
  plan:
  - get: resource-dev-integration-code
  - get: resource-main-code
    passed: [deploy-dev-space]
  - get: resource-deploy-dev
    trigger: true
    passed: [deploy-dev-space]
  - get: version
    params: {pre: rc}
  - task: perform-integration-tests
    file: resource-main-code/scripts/ci/dev-integration-tests.yml
  - put: version
    params: {file: version/number}
#  - put: resource-main-code
#    params: {repository: out/number}

# Deploy to the PCF test space
- name: deploy-test-space
  plan:
  - get: resource-main-code
  - get: resource-deploy-dev
    trigger: true
    passed: [dev-integration-tests]
  - get: artifact
  - put: resource-deploy-test
    params:
      manifest: resource-main-code/manifest-test.yml
      path: artifact/*.jar 
      
# Checkout and run test suite integration suite
- name: test-integration-tests
  serial: true
  plan:
  - get: resource-main-code
  - get: resource-test-integration-code
  - get: resource-deploy-test
    trigger: true
    passed: [deploy-test-space]
  - task: perform-integration-tests
    file: resource-main-code/scripts/ci/test-integration-tests.yml