resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: latest

# Your main repository that builds a spring boot jar that you wish to deploy to cloud foundry
resources:
- name: resource-main-code
  type: git
  source: 
    ignore_paths: [version]
    uri: https://git.ipacc.com/DuncanDA/concourse-cf-policynoteboot.git
    username: ((gitlab-username))
    password: ((gitlab-access-token))

# Your first set of integration tests location
- name: resource-dev-integration-code
  type: git
  source:
    uri: https://git.ipacc.com/DuncanDA/policynoteboot-integration.git
    username: ((gitlab-username))
    password: ((gitlab-access-token))
    
# Your second set of integration tests to run against the second environment once deployed
- name: resource-test-integration-code
  type: git
  source:
    uri: https://git.ipacc.com/DuncanDA/policynoteboot-integration.git
    username: ((gitlab-username))
    password: ((gitlab-access-token))
    
# The repository which will keep track of your version.  This can be the same repo as your main code base or a different one.
- name: version
  type: semver
  source:
    driver: git
    uri: https://git.ipacc.com/DuncanDA/concourse-cf-policynoteboot.git
    branch: master
    file: version
    username: ((gitlab-username))
    password: ((gitlab-access-token))
    # this is needed below...
    git_user: ((gitlab-username))
    
# nexus repo for SNAPSHOTS. 
- name: artifact
  type: maven-resource
  source:
    url: http://maven01.ipacc.com:8081/nexus/content/repositories/infinity-releases
    snapshot_url: http://maven01.ipacc.com:8081/nexus/content/repositories/infinity-snapshots
    artifact: ((nexus-artifact-name))
    username: ((nexus-username))
    password: ((nexus-password))
    
# PCF Deployment to Dev Space Resource
- name: resource-deploy-dev
  type: cf
  source:
    api: ((pws-api-dev))
    username: ((cf-username-dev))
    password: ((cf-password-dev))
    organization: ((pws-organization-dev))
    space: ((pws-space-dev))

# PCF Deployment to Test Space Resource
- name: resource-deploy-test
  type: cf
  source:
    api: ((pws-api-test))
    username: ((cf-username-test))
    password: ((cf-password-test))
    organization: ((pws-organization-test))
    space: ((pws-space-test))
          
jobs:
# build the artifiact, run unit tests, and deploy the SNAPSHOT artifact to nexus
- name: build-and-unit-test
  serial: true
  plan: 
  - get: version
    params: {bump: patch}
  - get: resource-main-code
    trigger: true
  - task: build
    # produces a folder named /out with the manifest.yml and app.jar in it that was built
    file: resource-main-code/scripts/ci/build-and-unit-test.yml
  # Add the patch version to git
  - put: version
    params: {file: version/number}
  # Upload the produced artifact to Nexus as a SNAPSHOT (SNAPSHOT created via the build.sh file).
  - put: artifact
    params:
      # app.jar and pom.xml is created in the build.sh script which is invoked via the build-and-unit-test.yml
      file: out/app.jar
      pom_file: out/pom.xml

# Deploy to PCF Dev space
- name: deploy-dev-space
  plan:
  - get: resource-main-code
  - task: app-manifest-prep-dev
    file: resource-main-code/scripts/ci/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix-dev))
  - get: artifact
    trigger: true
    passed: [build-and-unit-test]
  - put: resource-deploy-dev
    params:
      manifest: app-manifest-output/manifest.yml
      path: artifact/*.jar

# Checkout and run dev suite integration tests    
- name: dev-integration-tests
  serial: true
  plan:
  - get: resource-dev-integration-code
  - get: resource-main-code
    passed: [deploy-dev-space]
  - get: resource-deploy-dev
    trigger: true
    passed: [deploy-dev-space]
  - task: perform-integration-tests
    file: resource-main-code/scripts/ci/dev-integration-tests.yml
    params:
      # Pass in the url that our intergration tests will run against
      APP_ROUTE: https://((pws-app-suffix-dev)).((pws-app-domain-dev))

# Deploy to the PCF test space
- name: deploy-test-space
  plan:
  - get: resource-main-code
  - task: app-manifest-prep-test
    file: resource-main-code/scripts/ci/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix-test))
  - get: resource-deploy-dev
    trigger: true
    passed: [dev-integration-tests]
  - get: artifact
  - put: resource-deploy-test
    params:
      manifest: app-manifest-output/manifest.yml
      path: artifact/*.jar 
      
# Checkout and run test suite integration suite
- name: test-integration-tests
  serial: true
  plan:
  - get: resource-main-code
  - get: resource-test-integration-code
  - get: resource-deploy-test
    trigger: true
    passed: [deploy-test-space]
  - task: perform-integration-tests
    file: resource-main-code/scripts/ci/test-integration-tests.yml
    params:
      # Pass in the url that our intergration tests will run against
      APP_ROUTE: https://((pws-app-suffix-test)).((pws-app-domain-test))
    
- name: bump-minor-version
  serial: true
  plan:
  - get: resource-deploy-test
    trigger: true
    passed: [test-integration-tests]
  - get: version
    params: {bump: minor}
  - get: resource-main-code
  - get: artifact
  - task: create-release-artifact
    file: resource-main-code/scripts/ci/create-nexus-artifact.yml
    # Upload the minor release version again so we know where we left off last time
  - put: version
    params: {file: version/number}